baseURL = "https://mobiledge.github.io/blog/"
languageCode = "en-us"
title = "Notes & Posts"
theme = "hugo-book"

[params]
  BookSection = "posts"
  BookToC = false
  BookSearch = false
  BookDateFormat = "January 2, 2006"

[markup.goldmark.renderer]
  unsafe = true
